/* Database schema to keep the structure of entire database. */
CREATE DATABASE vet_clinic;
/*----------------Create Animals Table----------------*/
CREATE TABLE animals (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(25),
  date_of_birth DATE,
  escape_attempts INTEGER,
  neutered BOOLEAN,
  weight_kg DECIMAL(5, 2)
);

ALTER TABLE animals ADD COLUMN species VARCHAR(25);

/*--------------------Create Owners Table-----------------------*/
CREATE TABLE owners (
  id SERIAL PRIMARY KEY,
  full_name VARCHAR(50),
  age INTEGER
);
/*--------------------Create Species Table-----------------------*/
CREATE TABLE species (
  id SERIAL PRIMARY KEY,
  name VARCHAR(50)
);

/*-------------------Alter Animals Table-------------------------*/
ALTER TABLE animals ADD PRIMARY KEY (Id);
ALTER TABLE animals DROP COLUMN species;
ALTER TABLE animals ADD COLUMN species_id INTEGER REFERENCES species(id);
ALTER TABLE animals ADD COLUMN owner_id INTEGER REFERENCES owners(id);